# Generated by Django 2.2.1 on 2019-05-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_id', models.PositiveSmallIntegerField(default=0, primary_key='true', serialize=False)),
                ('categorie_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('user_role_id', models.PositiveSmallIntegerField(default=0, primary_key='true', serialize=False)),
                ('user_role_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('user_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User_role')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_name', models.CharField(blank=True, max_length=16, null=True)),
                ('blog_description', models.CharField(blank=True, max_length=64, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(editable=False, max_length=50)),
                ('modified_by', models.CharField(editable=False, max_length=50)),
                ('categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categories')),
            ],
        ),
    ]
